services:
  frontend:
    restart: unless-stopped
    image: codeberg.org/wafrn/wafrn-frontend:${IMAGE_TAG:-main}
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    env_file: .env
    environment:
      BACKEND_HOST: "${BACKEND_HOST:-wafrn-backend-1:9000 wafrn-backend-2:9000 wafrn-backend-3:9000}"
      WEBSOCKET_HOST: "wafrn-websocket-1:9000"
      AUTO_HTTPS_MODE: ${AUTO_HTTPS_MODE:-auto_https off}
    volumes:
      - ./packages/frontend/overrides:/overrides
      - frontend:/var/www/html/frontend
      - ./packages/backend/uploads:/var/www/html/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
      ### Development tip:
      ### Uncomment this section to use all the parts locally without having to configure domains for each one
      # - 8080:8080 # main process, backend and frontend
      # - 8081:8081 # cache
      # - 8082:8082 # media
      # - 8083:8083 # grafana
      # - 8084:8084 # bullboard
      # - 3000:3000 # PDS

  backend: &default_backend
    image: codeberg.org/wafrn/wafrn-backend:${IMAGE_TAG:-main}
    build: &default_backend_build
      context: .
      dockerfile: packages/backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      frontend:
        condition: service_started
      migration:
        condition: service_completed_successfully
    restart: unless-stopped
    env_file: .env
    environment: &default_backend_env_vars
      FRONTEND_FQDN_URL: https://${DOMAIN_NAME}
      USE_WORKERS: ${USE_WORKERS:-false}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    deploy:
      mode: replicated
      replicas: ${BACKEND_REPLICAS:-3}
    volumes:
      - ./packages/backend/uploads:/app/packages/backend/uploads
      - cache:/app/packages/backend/cache
      # NOTE: backend needs to have frontend (the compiled one) mounted
      # in order to serve rich link previews in messaging apps
      - frontend:/app/packages/frontend:ro

  workers:
    <<: *default_backend
    build:
      <<: *default_backend_build
    environment:
      <<: *default_backend_env_vars
      USE_WORKERS: true
    deploy:
      mode: replicated
      replicas: ${WORKERS_REPLICAS:-3}

  websocket:
    <<: *default_backend
    deploy:
      mode: replicated
      replicas: 1
    command: "npm exec tsx websocket.ts"

  migration:
    <<: *default_backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      frontend:
        condition: service_started
    restart: no
    deploy:
      mode: replicated
      replicas: 1
    command: "npm exec tsx migrate.ts init-container"

  db:
    build:
      context: monitoring/database
      dockerfile: Dockerfile
    # command: -c 'max_connections=500'
    restart: unless-stopped
    shm_size: "${SHM_SIZE:-2gb}"
    env_file: .env
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - dbpg:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped

  redis:
    image: redis:8.4
    restart: unless-stopped
    volumes:
      - redis:/data

  pds:
    image: ghcr.io/bluesky-social/pds:0.4
    restart: unless-stopped
    ports:
      - ${PDS_HTTP_PORT:-127.0.0.1:3000}:3000
    profiles: [bluesky]
    env_file: .env
    environment:
      PDS_HOSTNAME: ${PDS_DOMAIN_NAME}
      # all other env variables defined in .env file
    volumes:
      - pds:/pds

  pds_worker:
    <<: *default_backend
    profiles: [bluesky]
    deploy:
      mode: replicated
      replicas: 1
    command: "npm exec tsx atproto.ts"

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    profiles: [metrics]
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor:latest
    profiles: [metrics]
    command:
      - "-port=8081"
    environment:
      CADVISOR_HEALTHCHECK_URL: http://localhost:8081/healthz
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    restart: unless-stopped
    image: prom/node-exporter:latest
    profiles: [metrics]
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  grafana:
    build:
      context: monitoring/grafana
      dockerfile: Dockerfile
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    profiles: [metrics]
    env_file: .env

  pgwatch:
    build:
      context: monitoring/pgwatch
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DBNAME}
    restart: unless-stopped
    profiles: [metrics]
    env_file: .env
    command:
      - "--web-disable=all"
      - "--sources=/sources.yaml"
      - "--sink=postgresql://${POSTGRES_METRICS_USER}:${POSTGRES_METRICS_PASSWORD}@db:5432/${POSTGRES_METRICS_DBNAME}"
    depends_on:
      db:
        condition: service_healthy

  bullboard:
    container_name: bullboard
    image: nauverse/bull-board
    restart: unless-stopped
    profiles: [metrics]
    environment:
      REDIS_URL: redis:6379
      BULL_PREFIX: bull
      AUTH_REQUIRE: true
      USER_USERNAME: admin
      USER_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - redis

volumes:
  dbpg:
  pds:
  frontend:
  redis:
  prometheus_data:
  grafana_data:
  cache:

networks:
  default:
    enable_ipv6: true
