services:
  backend: &default_backend
    build: &default_backend_build
      context: .
      dockerfile: packages/backend/Dockerfile
      # these args configure private env vars for the backend and public env vars for the frontend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      frontend:
        condition: service_started
      migration:
        condition: service_completed_successfully
    restart: unless-stopped
    env_file: .env
    environment: &default_backend_env_vars
      FRONTEND_FQDN_URL: https://${DOMAIN_NAME}
      USE_WORKERS: false

    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - ./packages/backend/uploads:/app/packages/backend/uploads
      - cache:/app/packages/backend/cache
      - frontend:/app/packages/frontend:ro

  migration:
    <<: *default_backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      frontend:
        condition: service_started
    restart: no
    deploy:
      mode: replicated
      replicas: 1
    command: "npm exec tsx migrate.ts init-container"


  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    env_file: .env
    environment:
      BACKEND_HOST: "wafrn-backend-1:9000 wafrn-backend-2:9000 wafrn-backend-3:9000"
      CACHE_HOST: "cache:9000"
      WEBSOCKET_HOST: "wafrn-websocket-1:9000"
    volumes:
      - "caddy:/data"
      - "frontend:/var/www/html/frontend"
      - ./packages/backend/uploads:/var/www/html/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
      - 443:443

  db:
    build:
      context: monitoring/database
      dockerfile: Dockerfile
    #command: -c 'max_connections=500'
    restart: unless-stopped
    shm_size: '2gb'
    env_file: .env
    volumes:
      - dbpg:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped

  redis:
    image: redis:8.4
    restart: unless-stopped
    volumes:
      - redis:/data

  pds:
    image: ghcr.io/bluesky-social/pds:0.4
    restart: unless-stopped
    profiles:
      - bluesky
    env_file: .env
    ports:
      - localhost:3000:3000
    environment:
      PDS_DATA_DIRECTORY: /pds
      PDS_BLOBSTORE_DISK_LOCATION: /pds/blocks
      PDS_BLOB_UPLOAD_LIMIT: 157286400
      PDS_DID_PLC_URL: "https://plc.directory"
      PDS_BSKY_APP_VIEW_URL: ${PDS_APPVIEW_URL:-https://api.bsky.app}
      PDS_BSKY_APP_VIEW_DID: ${PDS_APPVIEW_DID:-did:web:api.bsky.app}
      PDS_REPORT_SERVICE_URL: ${PDS_MOD_URL:-https://mod.bsky.app}
      PDS_REPORT_SERVICE_DID: ${PDS_MOD_DID:-did:plc:ar7c4by46qjdydhdevvrndac}
      PDS_CRAWLERS: ${PDS_CRAWLERS:-https://bsky.network, https://atproto.africa}
      PDS_SERVICE_HANDLE_DOMAINS: ${PDS_HANDLE_DOMAINS:-.${PDS_DOMAIN_NAME}}
      PDS_EMAIL_SMTP_URL: "smtps://${SMTP_USER}:${SMTP_PASSWORD}@${SMTP_HOST}:${SMTP_PORT}"
      PDS_EMAIL_FROM_ADDRESS: "${SMTP_FROM}"
      LOG_ENABLED: true
    volumes:
      - pds:/pds

  pds_worker:
    <<: *default_backend
    profiles:
      - bluesky
    deploy:
      mode: replicated
      replicas: 1
    command: "npm exec tsx atproto.ts"
  websocket:
    <<: *default_backend
    deploy:
      mode: replicated
      replicas: 1
    command: "npm exec tsx websocket.ts"

  workers:
    <<: *default_backend
    build:
      <<: *default_backend_build
    environment:
      <<: *default_backend_env_vars
      USE_WORKERS: true
    deploy:
      mode: replicated
      replicas: 3

volumes:
  dbpg:
  caddy:
  pds:
  frontend:
  redis:
  cache:


networks:
  default:
    enable_ipv6: true
